name: igzut
description: "igzut"
publish_to: 'none' 

version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  gzu_zf_core:
    path: ../gzu_zf_core

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.4
  logger: ^2.5.0
  get: ^4.6.6
  url_launcher: ^6.3.1
  flutter_displaymode: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSerif 
      fonts:
        - asset: fonts/NotoSerif-VariableFont_wdth,wght.ttf
